apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: k9-dokgen+
  namespace: {{namespace}}
  labels:
    team: k9saksbehandling
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 80
  liveness:
    path: internal/actuator/health
    initialDelay: 30
    timeout: 10
  readiness:
    path: internal/actuator/info
    initialDelay: 30
    timeout: 10
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/{{cluster}}/fss/k9-dokgen/{{namespace}}
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: {{serviceuserkv}}
  prometheus:
    enabled: true
    path: /internal/prometheus
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  env:
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
