apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: k9-dokgen
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 80
  liveness:
    path: actuator/health
    initialDelay: 30
    timeout: 10
  readiness:
    path: actuator/info
    initialDelay: 30
    timeout: 10
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
      {{#each accessPoliciesInbound as |inboundRule|}}
        - application: {{inboundRule.application}}
          namespace: k9saksbehandling
          cluster: {{inboundRule.cluster}}
      {{/each}}
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  env:
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
